-- Postgres Schema for Nigeria LGA Master Dataset
-- Generated by AI Researcher Agent

CREATE TABLE IF NOT EXISTS lgas (
    lga_id VARCHAR(50) PRIMARY KEY, -- e.g. NG:LAG:IKEJA
    state_name VARCHAR(50) NOT NULL,
    lga_name VARCHAR(50) NOT NULL,
    headquarters_lat DECIMAL(9, 6),
    headquarters_lon DECIMAL(9, 6),
    website VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(50),
    data_collected_on DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS chairpersons (
    id SERIAL PRIMARY KEY,
    lga_id VARCHAR(50) REFERENCES lgas(lga_id),
    name VARCHAR(255) NOT NULL,
    title VARCHAR(100),
    party VARCHAR(50),
    term_start DATE,
    term_end DATE,
    verification_source_urls TEXT[] -- Array of URLs
);

CREATE TABLE IF NOT EXISTS key_officials (
    id SERIAL PRIMARY KEY,
    lga_id VARCHAR(50) REFERENCES lgas(lga_id),
    name VARCHAR(255) NOT NULL,
    position VARCHAR(100) NOT NULL,
    contact_info VARCHAR(255),
    source_urls TEXT[]
);

CREATE TABLE IF NOT EXISTS budgets (
    id SERIAL PRIMARY KEY,
    lga_id VARCHAR(50) REFERENCES lgas(lga_id),
    fiscal_year INTEGER NOT NULL,
    approved_amount_local NUMERIC(15, 2), -- NGN
    approved_amount_usd NUMERIC(15, 2),
    document_url VARCHAR(255),
    date_published DATE,
    source_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS projects (
    project_id VARCHAR(50) PRIMARY KEY, -- e.g., NG:LAG:IKEJA:PRJ:0001
    lga_id VARCHAR(50) REFERENCES lgas(lga_id),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) CHECK (status IN ('completed', 'ongoing', 'stalled', 'planned')),
    start_date DATE,
    end_date DATE,
    budgeted_cost_local NUMERIC(15, 2),
    funding_source VARCHAR(100),
    contractor VARCHAR(255),
    deliverables TEXT,
    evidence_urls TEXT[],
    last_verified_date DATE,
    confidence_score DECIMAL(3, 2), -- 0.00 to 1.00
    verification_notes TEXT
);

CREATE TABLE IF NOT EXISTS sources (
    source_id SERIAL PRIMARY KEY,
    url VARCHAR(500) UNIQUE NOT NULL,
    source_type VARCHAR(50) CHECK (source_type IN ('gov', 'media', 'ngo', 'tender_portal', 'budget_doc')),
    date_accessed DATE DEFAULT CURRENT_DATE,
    http_status INTEGER,
    lga_referenced VARCHAR(50)
);

-- Indexes for performance
CREATE INDEX idx_lgas_state ON lgas(state_name);
CREATE INDEX idx_projects_status ON projects(status);
